package com.shanthigear.dto;

import lombok.Data;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;

@Data
public class PayableItemDTO {
    @NotBlank(message = "Vendor number is required")
    private String vendorNumber;
    
    @NotBlank(message = "Vendor name is required")
    private String vendorName;
    
    private String vendorSite;
    
    @NotBlank(message = "Pay group is required")
    private String payGroup;
    
    @NotNull(message = "Amount is required")
    @DecimalMin(value = "0.01", message = "Amount must be greater than 0")
    private BigDecimal amountToPay;
    
    // Getters and setters are generated by Lombok @Data
}
